"""
SentinelAI Splunk Dashboard
LIVE MODE: Real-time MCP + Daemon Feed + Alerts + File Log Buffer
"""

import os
import json
import time
import pandas as pd
import streamlit as st

# ==========================================================
# PAGE CONFIG
# ==========================================================
st.set_page_config(
    page_title="SentinelAI Splunk Live Dashboard",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.title("⚙️ SentinelAI Splunk Live Stream")
st.caption("Real-time MCP → Splunk → Daemon Engine → Alert Pipeline")
st.divider()

# CONFIGURATION: Point this to where your daemon or system logs write
DAEMON_LOG_PATH = "splunk_daemon.log"


# ==========================================================
# DATA PARSING ENGINE (THREAD-SAFE STATE CAPTURE)
# ==========================================================
class LogParser:
    """
    Parses live file streams generated by SplunkDaemon into 
    structured metric buckets, raw terminal lines, and live alerts.
    """
    @staticmethod
    def fetch_live_data():
        metrics = {"auth": 0, "network": 0, "security": 0, "system": 0}
        alerts = []
        raw_terminal_lines = []

        if not os.path.exists(DAEMON_LOG_PATH):
            return metrics, alerts, ["Waiting for SplunkDaemon to spin up and write logs..."]

        try:
            with open(DAEMON_LOG_PATH, "r", encoding="utf-8", errors="ignore") as f:
                # Read last 250 lines to keep UI fast and lightweight
                lines = f.readlines()[-250:]
                
                for line in lines:
                    clean_line = line.strip()
                    if not clean_line:
                        continue
                    
                    raw_terminal_lines.append(clean_line)

                    # Intercept Summary Metric Payloads from Loguru outputs
                    if "📊 Summary:" in clean_line:
                        try:
                            # Isolate JSON dictionary payload string
                            json_str = clean_line.split("📊 Summary:")[-1].strip().replace("'", '"')
                            summary_data = json.loads(json_str)
                            # Cumulative or latest cycle event distribution simulation
                            metrics["system"] += summary_data.get("events", 0)
                        except Exception:
                            pass

                    # Parse Event Counts dynamically out of standard log strings
                    if "Parallel collection complete:" in clean_line:
                        try:
                            count = int(clean_line.split("complete:")[-1].split("events")[0].strip())
                            metrics["system"] = max(metrics["system"], count)
                        except Exception:
                            pass

                    # Intercept live daemon anomaly warnings and push directly to Dashboard alerts
                    if "🚨 Detected" in clean_line:
                        try:
                            anomaly_count = clean_line.split("Detected")[-1].split("anomalies")[0].strip()
                            if int(anomaly_count) > 0:
                                alerts.append({
                                    "message": f"SplunkDaemon pipeline flagged {anomaly_count} micro-anomalies during processing."
                                })
                        except Exception:
                            pass
                            
                    if "Alert push failed" in clean_line:
                        alerts.append({"message": "GlobalAlertStore dispatch pipeline congestion detected."})

        except Exception as e:
            raw_terminal_lines.append(f"[DASHBOARD ERROR] Failed reading pipeline logs: {e}")

        # Keep tail optimization sane for standard output UI
        return metrics, alerts, raw_terminal_lines[-40:]


# ==========================================================
# RUN PARSER EXECUTION
# ==========================================================
auth_events, alerts, terminal_feed = LogParser.fetch_live_data()


# ==========================================================
# UI COMPONENTS: LIVE METRICS
# ==========================================================
col1, col2, col3, col4 = st.columns(4)

# The Daemon groups strings downstream dynamically. 
# We pull metrics parsed out of real-time terminal evaluation streams.
col1.metric("Auth Pipelines", auth_events.get("auth", 0))
col2.metric("Network Interfaces", auth_events.get("network", 0))
col3.metric("Security Agents", auth_events.get("security", 0))
col4.metric("Engine Managed Events", auth_events.get("system", 0))

st.divider()


# ==========================================================
# UI COMPONENTS: ALERT ENGINE LIVE FEED
# ==========================================================
st.subheader("🚨 Real-time Engine Anomalies")

if alerts:
    for alert in alerts[-4:]:
        st.error(f"⚠️ {alert.get('message', 'Suspicious pipeline shift flagged.')}")
else:
    st.success("System Stable — Zero active daemon anomaly blocks intercepted.")


# ==========================================================
# UI COMPONENTS: LIVE HISTOGRAM GRAPH
# ==========================================================
st.subheader("📈 Core Event Processing Density")

df = pd.DataFrame({
    "Pipeline Engine Source": ["Auth Module", "Network Module", "Security Module", "Core System Daemon"],
    "Intercepted Event Count": [
        auth_events.get("auth", 0),
        auth_events.get("network", 0),
        auth_events.get("security", 0),
        max(auth_events.get("system", 0), 1) # Default baseline visual representation
    ]
})

st.bar_chart(df.set_index("Pipeline Engine Source"))


# ==========================================================
# UI COMPONENTS: LIVE TERMINAL OUTPUT VIEW
# ==========================================================
st.divider()
st.subheader("💻 Live Splunk Daemon Terminal Feed")

log_block = "\n".join(terminal_feed)
st.code(log_block if log_block else "Stdout pipeline standard buffer clean.", language="bash")


# ==========================================================
# PERSISTENT AUTO-REFRESH CONFIGURATION
# ==========================================================
# Match daemon poll intervals gracefully without bottlenecking client-side execution threads
time.sleep(2)
st.rerun()